# Generated by Django 2.2.24 on 2022-04-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miosito_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFatti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
            ],
        ),
    ]
