# Generated by Django 2.2.24 on 2022-04-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miosito_app', '0003_auto_20220430_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devtools',
            old_name='type',
            new_name='frontend',
        ),
        migrations.RenameField(
            model_name='languages',
            old_name='type',
            new_name='frontend',
        ),
    ]
